import type { Avatar } from "@/types/avatar"

export const avatars: Avatar[] = [
  {
    id: "1",
    name: "Ava SEO",
    role: "SEO Specialist",
    functions: ["Keyword Research", "Content Optimization", "Backlink Analysis", "Technical SEO Audits"],
    image: "https://images.tech.co/wp-content/uploads/2024/04/17123134/AdobeStock_657290983-1-min-708x400.jpeg",
    required_plan: "small",
    description: "Expert in driving organic traffic and improving search engine rankings for businesses of all sizes.",
    created_at: "2025-08-01T12:00:00.000Z",
    updated_at: "2025-08-01T12:00:00.000Z",
  },
  {
    id: "2",
    name: "Mark Ads",
    role: "Ads Campaign Manager",
    functions: ["PPC Strategy", "Ad Copywriting", "Audience Targeting", "Performance Tracking"],
    image: "https://images.tech.co/wp-content/uploads/2024/04/17123134/AdobeStock_657290983-1-min-708x400.jpeg",
    required_plan: "small",
    description: "Specializes in creating high-performing ad campaigns across various platforms to maximize ROI.",
    created_at: "2025-08-01T12:00:00.000Z",
    updated_at: "2025-08-01T12:00:00.000Z",
  },
  {
    id: "3",
    name: "Ulysses UX",
    role: "UX Designer",
    functions: ["User Research", "Wireframing", "Prototyping", "Usability Testing"],
    image: "https://images.tech.co/wp-content/uploads/2024/04/17123134/AdobeStock_657290983-1-min-708x400.jpeg",
    required_plan: "small",
    description:
      "Focuses on designing intuitive and engaging user experiences that delight customers and drive conversions.",
    created_at: "2025-08-01T12:00:00.000Z",
    updated_at: "2025-08-01T12:00:00.000Z",
  },
  {
    id: "4",
    name: "Penelope Copy",
    role: "Copywriter",
    functions: ["Sales Copy", "Blog Posts", "Website Content", "Email Campaigns"],
    image: "https://images.tech.co/wp-content/uploads/2024/04/17123134/AdobeStock_657290983-1-min-708x400.jpeg",
    required_plan: "medium",
    description:
      "Crafts compelling and persuasive copy that captures attention and motivates action across all marketing channels.",
    created_at: "2025-08-01T12:00:00.000Z",
    updated_at: "2025-08-01T12:00:00.000Z",
  },
  {
    id: "5",
    name: "Data Dan",
    role: "Data Analyst",
    functions: ["Market Research", "Trend Analysis", "Reporting", "Predictive Modeling"],
    image: "https://images.tech.co/wp-content/uploads/2024/04/17123134/AdobeStock_657290983-1-min-708x400.jpeg",
    required_plan: "medium",
    description:
      "Transforms complex data into actionable insights, helping businesses make informed strategic decisions.",
    created_at: "2025-08-01T12:00:00.000Z",
    updated_at: "2025-08-01T12:00:00.000Z",
  },
  {
    id: "6",
    name: "Social Sam",
    role: "Social Media Strategist",
    functions: ["Content Calendar", "Engagement Tactics", "Platform Management", "Influencer Outreach"],
    image: "https://avatar.iran.liara.run/public/50",
    required_plan: "medium",
    description:
      "Develops and executes winning social media strategies to build brand presence and foster community engagement.",
    created_at: "2025-08-01T12:00:00.000Z",
    updated_at: "2025-08-01T12:00:00.000Z",
  },
  {
    id: "7",
    name: "Devon Dev",
    role: "Web Developer",
    functions: ["Frontend Development", "Backend Integration", "API Development", "Performance Optimization"],
    image: "https://avatar.iran.liara.run/public/51",
    required_plan: "big",
    description:
      "Builds robust and scalable web applications, ensuring seamless functionality and exceptional user experience.",
    created_at: "2025-08-01T12:00:00.000Z",
    updated_at: "2025-08-01T12:00:00.000Z",
  },
  {
    id: "8",
    name: "Content Carla",
    role: "Content Strategist",
    functions: ["Content Planning", "Editorial Calendar", "Audience Segmentation", "Distribution Channels"],
    image: "https://avatar.iran.liara.run/public/52",
    required_plan: "big",
    description:
      "Designs comprehensive content strategies that align with business goals and resonate with target audiences.",
    created_at: "2025-08-01T12:00:00.000Z",
    updated_at: "2025-08-01T12:00:00.000Z",
  },
  {
    id: "9",
    name: "PR Paul",
    role: "Public Relations Expert",
    functions: ["Media Relations", "Crisis Management", "Press Release Writing", "Brand Reputation"],
    image: "https://avatar.iran.liara.run/public/53",
    required_plan: "big",
    description:
      "Manages public perception and builds strong relationships with media to enhance brand reputation and visibility.",
    created_at: "2025-08-01T12:00:00.000Z",
    updated_at: "2025-08-01T12:00:00.000Z",
  },
  {
    id: "10",
    name: "Legal Leo",
    role: "Legal Advisor",
    functions: ["Compliance Checks", "Contract Review", "Intellectual Property", "Privacy Policies"],
    image: "https://avatar.iran.liara.run/public/54",
    required_plan: "big",
    description:
      "Provides expert legal guidance to ensure compliance, protect assets, and mitigate risks for businesses.",
    created_at: "2025-08-01T12:00:00.000Z",
    updated_at: "2025-08-01T12:00:00.000Z",
  },
]