import { Home, ShoppingBag, Plane, Shirt, Laptop, BookOpen, Utensils, Car, Gift, Heart } from 'lucide-react'

export const categories = [
  { name: "All Categories", icon: Home },
  { name: "Electronics", icon: Laptop },
  { name: "Fashion", icon: Shirt },
  { name: "Travel", icon: Plane },
  { name: "Books", icon: BookOpen },
  { name: "Food & Drink", icon: Utensils },
  { name: "Automotive", icon: Car },
  { name: "Gifts", icon: Gift },
  { name: "Health & Beauty", icon: Heart },
]

export const webshops = [
  {
    id: "1",
    name: "TechMart",
    logo: "/placeholder.svg?height=60&width=60",
    cashback: "5% Cashback",
    description: "Your go-to for the latest gadgets.",
    category: "Electronics",
  },
  {
    id: "2",
    name: "Fashionista",
    logo: "/placeholder.svg?height=60&width=60",
    cashback: "10% Cashback",
    description: "Trendy apparel for every style.",
    category: "Fashion",
    },
  {
    id: "3",
    name: "TravelNow",
    logo: "/placeholder.svg?height=60&width=60",
    cashback: "$25 Cashback",
    description: "Book your next adventure with us.",
    category: "Travel",
  },
  {
    id: "4",
    name: "Bookworm Haven",
    logo: "/placeholder.svg?height=60&width=60",
    cashback: "7% Cashback",
    description: "Dive into a world of stories.",
    category: "Books",
  },
  {
    id: "5",
    name: "Gourmet Delights",
    logo: "/placeholder.svg?height=60&width=60",
    cashback: "8% Cashback",
    description: "Fine foods delivered to your door.",
    category: "Food & Drink",
  },
  {
    id: "6",
    name: "AutoParts Pro",
    logo: "/placeholder.svg?height=60&width=60",
    cashback: "6% Cashback",
    description: "Quality parts for your vehicle.",
    category: "Automotive",
  },
  {
    id: "7",
    name: "Giftopia",
    logo: "/placeholder.svg?height=60&width=60",
    cashback: "12% Cashback",
    description: "Perfect gifts for every occasion.",
    category: "Gifts",
  },
  {
    id: "8",
    name: "BeautyBloom",
    logo: "/placeholder.svg?height=60&width=60",
    cashback: "9% Cashback",
    description: "Enhance your natural glow.",
    category: "Health & Beauty",
  },
  {
    id: "9",
    name: "HomeDecor Hub",
    logo: "/placeholder.svg?height=60&width=60",
    cashback: "7% Cashback",
    description: "Transform your living space.",
    category: "Home & Garden",
  },
  {
    id: "10",
    name: "Sporty Gear",
    logo: "/placeholder.svg?height=60&width=60",
    cashback: "8% Cashback",
    description: "Equip yourself for victory.",
    category: "Sports & Outdoors",
  },
]
